# SPDX-License-Identifier: Apache-2.0
# Copyright 2021 Christian Perwass

"""Regression tests for the PGA complement dual (J‑map / Hodge star).

Covers the Dorst/Gunn ``dual``/``undual`` conventions for the null‑vector
PGA bases (see ``dev/todos/pga-dual-undual-fix.md``):

- ``dual()`` is the J‑map / Hodge star and satisfies ``x ∧ dual(x) = +I``
  for **every** subspace blade (Dorst ``PGA4CS`` §9.1, Table 4).
- ``undual()`` is the Hodge undualization ``⋆⁻¹`` — the true inverse of
  ``dual()``.  For 4D PGA this is ``grade_involution ∘ dual``; for 3D PGA
  (2D Euclidean) the J‑map is involutive so ``undual == dual``.
"""

from __future__ import annotations

import pytest

from pytanga.basis import BasisPGA2, BasisPGA3


# Skip all tests that instantiate a Basis class (requires C++ compilation) when
# the build infrastructure is broken (e.g. python3.12-dev / Python.h missing).
def _build_ok() -> bool:
    try:
        BasisPGA3()
        return True
    except Exception:
        return False


_NEEDS_BUILD = pytest.mark.skipif(
    not _build_ok(),
    reason="C++ extension build unavailable (python3.12-dev / Python.h missing)",
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _subspace_blades(alg, vectors):
    """All subspace blades generated by *vectors* (one blade per bitmask)."""
    n = len(vectors)
    out = []
    for mask in range(1 << n):
        blade = None
        for i in range(n):
            if mask & (1 << i):
                blade = vectors[i] if blade is None else blade.op(vectors[i])
        if blade is None:
            blade = alg.multivector({0: 1.0})
        out.append((mask, blade))
    return out


def _assert_equal(a, b, msg: str = "") -> None:
    assert (a - b).is_zero, f"{msg}\n  left:  {a!r}\n  right: {b!r}"


# ---------------------------------------------------------------------------
# 4D PGA (3D Euclidean) — BasisPGA3
# ---------------------------------------------------------------------------


@_NEEDS_BUILD
class TestPGA3Dual:
    def setup_method(self):
        self.b = BasisPGA3()
        self.vectors = [self.b.e0, self.b.e1, self.b.e2, self.b.e3]
        self.I = self.b.e0.op(self.b.e1).op(self.b.e2).op(self.b.e3)

    def test_dual_satisfies_wedge_identity(self):
        """x ∧ dual(x) == +I₄ for every subspace blade (Dorst Table 4)."""
        for mask, x in _subspace_blades(self.b, self.vectors):
            _assert_equal(x.op(x.dual()), self.I, f"mask={mask}")

    def test_undual_is_inverse_of_dual(self):
        """undual(dual(x)) == x for every subspace blade."""
        for mask, x in _subspace_blades(self.b, self.vectors):
            _assert_equal(x.dual().undual(), x, f"mask={mask}")

    def test_dual_is_inverse_of_undual(self):
        """dual(undual(x)) == x for every subspace blade."""
        for mask, x in _subspace_blades(self.b, self.vectors):
            _assert_equal(x.undual().dual(), x, f"mask={mask}")

    def test_dual_matches_dorst_table4(self):
        """Pin the signed J‑map to Dorst's Table 4 (PGA4CS §9.1)."""
        e0, e1, e2, e3 = self.vectors
        scalar = self.b.multivector({0: 1.0})

        _assert_equal(scalar.dual(), self.I)  # ⋆1 = e0123
        _assert_equal(e0.dual(), e1.op(e2).op(e3))  # ⋆e0 = e123
        _assert_equal(e1.dual(), e0.op(e3).op(e2))  # ⋆e1 = e032 = −e023
        _assert_equal(e2.dual(), e0.op(e1).op(e3))  # ⋆e2 = e013
        _assert_equal(e3.dual(), e0.op(e2).op(e1))  # ⋆e3 = e021 = −e012
        _assert_equal(e0.op(e1).dual(), e2.op(e3))  # ⋆e01 = e23
        _assert_equal(e0.op(e2).dual(), e3.op(e1))  # ⋆e02 = e31 = −e13
        _assert_equal(e0.op(e3).dual(), e1.op(e2))  # ⋆e03 = e12


# ---------------------------------------------------------------------------
# 3D PGA (2D Euclidean) — BasisPGA2
# ---------------------------------------------------------------------------


@_NEEDS_BUILD
class TestPGA2Dual:
    def setup_method(self):
        self.b = BasisPGA2()
        self.vectors = [self.b.e0, self.b.e1, self.b.e2]
        self.I = self.b.e0.op(self.b.e1).op(self.b.e2)

    def test_dual_satisfies_wedge_identity(self):
        """x ∧ dual(x) == +I₃ for every subspace blade (2D PGA table)."""
        for mask, x in _subspace_blades(self.b, self.vectors):
            _assert_equal(x.op(x.dual()), self.I, f"mask={mask}")

    def test_undual_is_inverse_of_dual(self):
        """undual(dual(x)) == x for every subspace blade."""
        for mask, x in _subspace_blades(self.b, self.vectors):
            _assert_equal(x.dual().undual(), x, f"mask={mask}")

    def test_dual_is_inverse_of_undual(self):
        """dual(undual(x)) == x for every subspace blade."""
        for mask, x in _subspace_blades(self.b, self.vectors):
            _assert_equal(x.undual().dual(), x, f"mask={mask}")

    def test_dual_matches_2d_table(self):
        """Pin the signed J‑map to the 2D PGA table (PGA4CS §9.1)."""
        e0, e1, e2 = self.vectors
        scalar = self.b.multivector({0: 1.0})

        _assert_equal(scalar.dual(), self.I)  # ⋆1 = e012
        _assert_equal(e0.dual(), e1.op(e2))  # ⋆e0 = e12
        _assert_equal(e1.dual(), -(e0.op(e2)))  # ⋆e1 = −e02
        _assert_equal(e2.dual(), e0.op(e1))  # ⋆e2 = e01
        _assert_equal(e0.op(e1).dual(), e2)  # ⋆e01 = e2
        _assert_equal(e0.op(e2).dual(), -e1)  # ⋆e02 = −e1
        _assert_equal(e1.op(e2).dual(), e0)  # ⋆e12 = e0
