# SPDX-License-Identifier: Apache-2.0
# Copyright 2021 Christian Perwass

"""Typed protocols describing the generated C++ algebra binding.

``get_or_build`` emits a per-``(dim, sig, dtype)`` extension module at runtime,
so it carries no static type information.  Without a description every
``Algebra._mod`` / ``MV._impl`` access is ``Unknown`` for a type checker, which
makes ``unsound-return-statement`` fire on every wrapper method.

These two protocols give ``ty`` a view of the generated module and its
``DynMV`` class, so the Python wrappers in ``pytanga.algebra`` type-check
without suppressions.

The signatures below are transcribed from ``py/pytanga/_template.cpp`` and the
``py/pytanga/codegen/*_def()`` snippets (the authoritative source).  Value types
are ``float | int`` because the same generator serves float and integer
algebras (the ``{CTYPE}`` placeholder).  Long argument lists that the Python
wrappers always forward verbatim use ``*args: Any`` — only the return types
matter for the diagnostics this module removes.
"""

from __future__ import annotations

from typing import Any, Protocol

import numpy as np


class DynMVBinding(Protocol):
    """The generated C++ ``DynMV`` multivector wrapped by :class:`MV`."""

    def set(self, blade_id: int, value: float | int) -> None: ...

    def get(self, blade_id: int) -> float | int: ...

    def to_dict(self) -> dict[int, float | int]: ...

    def from_dict(self, coeffs: dict[int, float | int]) -> None: ...

    def blade_count(self) -> int: ...

    def reset(self) -> None: ...

    def prune(self) -> None: ...


class AlgebraBinding(Protocol):
    """The generated C++ algebra module returned by ``get_or_build``."""

    # --- module-level constants (_template.cpp) ---------------------------
    VECTOR_SPACE_DIM: int
    ALGEBRA_DIM: int
    SIGNATURE: int
    PSEUDOSCALAR_ID: int

    # --- ``py::class_<TDynMV>`` constructor -------------------------------
    DynMV: type[DynMVBinding]

    # --- products ---------------------------------------------------------
    def gp(self, a: DynMVBinding, b: DynMVBinding) -> DynMVBinding: ...

    def op(self, a: DynMVBinding, b: DynMVBinding) -> DynMVBinding: ...

    def ip(self, a: DynMVBinding, b: DynMVBinding) -> DynMVBinding: ...

    def gp_mod(self, a: DynMVBinding, b: DynMVBinding, mod: int) -> DynMVBinding: ...

    def op_mod(self, a: DynMVBinding, b: DynMVBinding, mod: int) -> DynMVBinding: ...

    def ip_mod(self, a: DynMVBinding, b: DynMVBinding, mod: int) -> DynMVBinding: ...

    def inv(self, a: DynMVBinding, mod: int | None = None) -> DynMVBinding: ...

    def reduce(self, a: DynMVBinding, mod: int) -> DynMVBinding: ...

    def sp(self, a: DynMVBinding, b: DynMVBinding) -> float | int: ...

    def vp(self, versor: DynMVBinding, b: DynMVBinding) -> DynMVBinding: ...

    # --- linear operations -------------------------------------------------
    def add(self, a: DynMVBinding, b: DynMVBinding) -> DynMVBinding: ...

    def sub(self, a: DynMVBinding, b: DynMVBinding) -> DynMVBinding: ...

    def neg(self, a: DynMVBinding) -> DynMVBinding: ...

    def scale(self, a: DynMVBinding, s: float | int) -> DynMVBinding: ...

    def rev(self, a: DynMVBinding) -> DynMVBinding: ...

    def conj(self, a: DynMVBinding) -> DynMVBinding: ...

    # --- grade / scalar / dual --------------------------------------------
    def grade_proj(self, a: DynMVBinding, grade: int) -> DynMVBinding: ...

    def grades(self, a: DynMVBinding) -> list[int]: ...

    def is_grade(self, a: DynMVBinding, grade: int) -> bool: ...

    def is_zero(self, a: DynMVBinding) -> bool: ...

    def is_scalar(self, a: DynMVBinding) -> bool: ...

    def scalar(self, a: DynMVBinding) -> float | int: ...

    def magnitude(self, a: DynMVBinding) -> float: ...

    def magnitude_sq(self, a: DynMVBinding) -> float: ...

    def complement(self, a: DynMVBinding) -> DynMVBinding: ...

    def dual(self, a: DynMVBinding) -> DynMVBinding: ...

    def ldual(self, a: DynMVBinding) -> DynMVBinding: ...

    def project_onto(self, a: DynMVBinding, b: DynMVBinding) -> DynMVBinding: ...

    def project_onto_mask(self, a: DynMVBinding, ids: list[int]) -> DynMVBinding: ...

    # --- reverse / conjugate products -------------------------------------
    def gp_rev(
        self, a: DynMVBinding, rev_a: bool, b: DynMVBinding, rev_b: bool
    ) -> DynMVBinding: ...

    def gp_conj(
        self, a: DynMVBinding, conj_a: bool, b: DynMVBinding, conj_b: bool
    ) -> DynMVBinding: ...

    def ip_rev(
        self, a: DynMVBinding, rev_a: bool, b: DynMVBinding, rev_b: bool
    ) -> DynMVBinding: ...

    def ip_conj(
        self, a: DynMVBinding, conj_a: bool, b: DynMVBinding, conj_b: bool
    ) -> DynMVBinding: ...

    def op_rev(
        self, a: DynMVBinding, rev_a: bool, b: DynMVBinding, rev_b: bool
    ) -> DynMVBinding: ...

    def op_conj(
        self, a: DynMVBinding, conj_a: bool, b: DynMVBinding, conj_b: bool
    ) -> DynMVBinding: ...

    # --- blade operations --------------------------------------------------
    def blade_inverse(self, a: DynMVBinding) -> DynMVBinding: ...

    def blade_pseudo_inverse(self, a: DynMVBinding) -> DynMVBinding: ...

    def blade_factorize(self, a: DynMVBinding) -> list[DynMVBinding]: ...

    def blade_factorize_versor(
        self, a: DynMVBinding, eps: float, max_iterations: int
    ) -> tuple[DynMVBinding, list[DynMVBinding]]: ...

    def join(self, a: DynMVBinding, b: DynMVBinding) -> DynMVBinding: ...

    def meet(self, a: DynMVBinding, b: DynMVBinding) -> DynMVBinding: ...

    def blade_project(self, a: DynMVBinding, n: DynMVBinding) -> DynMVBinding: ...

    def blade_project_vec(
        self, vec: list[DynMVBinding], n: DynMVBinding
    ) -> list[DynMVBinding]: ...

    def blade_reject(self, a: DynMVBinding, n: DynMVBinding) -> DynMVBinding: ...

    def blade_reject_vec(
        self, vec: list[DynMVBinding], n: DynMVBinding
    ) -> list[DynMVBinding]: ...

    # --- blade masks -------------------------------------------------------
    def blade_mask(self, a: DynMVBinding, only_nonzero: bool) -> list[int]: ...

    # --- matrices / tensors ------------------------------------------------
    def to_matrix(self, *args: Any) -> np.ndarray: ...

    def to_matrix_batch(self, *args: Any) -> np.ndarray: ...

    def from_matrix(self, *args: Any) -> DynMVBinding: ...

    def from_matrix_batch(self, *args: Any) -> list[DynMVBinding]: ...

    def product_matrix_rev(self, *args: Any) -> np.ndarray: ...

    def product_matrix_conj(self, *args: Any) -> np.ndarray: ...

    def solve_mod(self, *args: Any) -> DynMVBinding: ...
