# SPDX-License-Identifier: Apache-2.0
# Copyright 2021 Christian Perwass

"""Interactive 3D visualization of geometric entities via Three.js.

Provides a zero-dependency (on the browser side) WebSocket + Three.js
pipeline for visualizing pytanga.geometry entities in a web browser.

Usage::

    from pytanga.viz import Visualizer, CameraConfig3d
    from pytanga.geometry import Point

    viz = Visualizer()
    viz.add(Point(1, 2, 3), color="#ff4444")
    viz.run()  # opens browser, blocks until Ctrl+C

    # Explicit camera settings
    viz = Visualizer(
        camera=CameraConfig3d(position=(10, 6, 12), target=(0, 0, 0), fov=50),
    )
    viz.run()
"""

from ._act_style import ActObjectStyle, ActPointStyle
from ._active import (
    ActClickHandler,
    ActEventHandler,
    ActHandler,
    ActPoint,
    ActSceneObject,
)
from ._anchor import EAnchor
from ._app import VisualizerApp
from ._banner import Banner
from ._colors import Color
from ._controls import (
    Button,
    Checkbox,
    ColorPicker,
    ControlEvent,
    ControlGroup,
    Dropdown,
    EControlVariant,
    FileChooser,
    Slider,
    Table,
    TableCellChange,
    TableColumnAdd,
    TableRowAdd,
    TableRowsDelete,
    TextArea,
    TextField,
    ValueEdit,
)
from ._coordinate_system import CoordinateSystem, fit_view2d
from ._dialog import Dialog
from ._figure import FigureConfig
from ._icons import EIconMaterial, EIconUC
from ._interaction import (
    Camera,
    ClickEvent,
    DragEvent,
    DragMode,
    Handler,
    InteractionConfig,
    InteractionEventType,
    InteractionHandlerRegistry,
    InteractionTrigger,
    ModifierKey,
    MouseButton,
    ScrollEvent,
)
from ._keys import KeyModifier
from ._label import Label
from ._nodes import VizGroup, VizOverlayObject, VizSceneObject
from ._object_ref import VizObjectRef
from ._point_path import PointPath, gradient_colors, multi_gradient_colors
from ._scale import LinearScale, LogScale, Scale
from ._scene_handle import VizSceneHandle
from ._scene_objects import Axes2D, Axes3D, Axis, Grid
from ._size import Size, SizeSpec
from ._styles import (
    AnimStyle,
    AnnotationStyle,
    ArcStyle,
    Axes2DStyle,
    Axes3DStyle,
    AxisStyle,
    BoxStyle,
    CircleStyle,
    CrossHairPointStyle,
    CylinderLineStyle,
    CylinderStyle,
    DashedWireframe,
    DilatorStyle,
    DirectionStyle,
    DiskStyle,
    DottedWireframe,
    EllipseStyle,
    EllipsoidStyle,
    FigureStyle,
    GeneralRotorStyle,
    GridStyle,
    HPointStyle,
    InversionStyle,
    LabelStyle,
    LineStyle,
    MotorStyle,
    ObjVizStyle,
    PartialDiskStyle,
    PlaneStyle,
    PointPairStyle,
    PointPathStyle,
    PointStyle,
    ReflectionLineStyle,
    ReflectionPlaneStyle,
    RegularPolygonStyle,
    RotorStyle,
    SdfBoxStyle,
    SdfCircleStyle,
    SdfCylinderStyle,
    SdfDiskStyle,
    SdfEllipseStyle,
    SdfEllipsoidStyle,
    SdfLineStyle,
    SdfPartialDiskStyle,
    SdfPlaneStyle,
    SdfPointStyle,
    SdfRegularPolygonStyle,
    SdfSphereStyle,
    SdfStyle,
    SolidWireframe,
    SpaceStyle,
    SphereStyle,
    TextureLabelStyle,
    TitleStyle,
    TranslatorStyle,
    VizStyle,
    WireframeDashPattern,
)
from ._themes import (
    copy_theme,
    default_theme,
    external_theme_dirs,
    list_themes,
    register_theme,
    theme_css_files,
    theme_label,
)
from ._types import SceneEntity, VizInputType
from ._viz_styles import VizStyles
from .camera import (
    CameraConfig,
    CameraConfig2d,
    CameraConfig3d,
    View2DConfig,
    View3dConfig,
    get_camera,
    get_camera_view2d,
    get_camera_view3d,
)
from .export._exporter import SceneExporter
from .scene import SceneConfig
from .views import (
    ButtonView,
    CheckboxView,
    ColorPickerView,
    ControlView,
    DropdownView,
    FileChooserView,
    GroupView,
    MenuView,
    SceneView,
    SliderView,
    SpacerView,
    SplitView,
    StackView,
    TableView,
    TextAreaView,
    TextFieldView,
    ValueEditView,
    View,
)
from .visualizer import Timeline, Visualizer

__all__ = [
    "ActClickHandler",
    "ActEventHandler",
    "ActHandler",
    "ActObjectStyle",
    "ActPoint",
    "ActPointStyle",
    "ActSceneObject",
    "AnimStyle",
    "AnnotationStyle",
    "ArcStyle",
    "Axes2D",
    "Axes2DStyle",
    "Axes3D",
    "Axes3DStyle",
    "Axis",
    "AxisStyle",
    "Banner",
    "BoxStyle",
    "Button",
    "ButtonView",
    "Camera",
    "CameraConfig",
    "CameraConfig2d",
    "CameraConfig3d",
    "Checkbox",
    "CheckboxView",
    "Color",
    "ColorPicker",
    "ColorPickerView",
    "CoordinateSystem",
    "ClickEvent",
    "ControlEvent",
    "CircleStyle",
    "ControlGroup",
    "fit_view2d",
    "ControlView",
    "GroupView",
    "MenuView",
    "CrossHairPointStyle",
    "CylinderLineStyle",
    "CylinderStyle",
    "DashedWireframe",
    "Dialog",
    "DilatorStyle",
    "DirectionStyle",
    "DiskStyle",
    "DottedWireframe",
    "DragEvent",
    "DragMode",
    "Dropdown",
    "DropdownView",
    "EAnchor",
    "EControlVariant",
    "EIconMaterial",
    "EIconUC",
    "EllipseStyle",
    "EllipsoidStyle",
    "FigureConfig",
    "FigureStyle",
    "FileChooser",
    "FileChooserView",
    "GeneralRotorStyle",
    "Grid",
    "GridStyle",
    "get_camera",
    "get_camera_view2d",
    "get_camera_view3d",
    "Handler",
    "HPointStyle",
    "InteractionConfig",
    "InteractionEventType",
    "InteractionHandlerRegistry",
    "InteractionTrigger",
    "InversionStyle",
    "KeyModifier",
    "Label",
    "LabelStyle",
    "LineStyle",
    "LinearScale",
    "LogScale",
    "ModifierKey",
    "MouseButton",
    "MotorStyle",
    "ObjVizStyle",
    "PartialDiskStyle",
    "PlaneStyle",
    "PointPath",
    "PointPathStyle",
    "PointPairStyle",
    "PointStyle",
    "ReflectionLineStyle",
    "ReflectionPlaneStyle",
    "RegularPolygonStyle",
    "RotorStyle",
    "Scale",
    "SceneConfig",
    "SceneEntity",
    "SceneExporter",
    "SceneView",
    "ScrollEvent",
    "SdfBoxStyle",
    "SdfCircleStyle",
    "SdfCylinderStyle",
    "SdfDiskStyle",
    "SdfEllipseStyle",
    "SdfEllipsoidStyle",
    "SdfLineStyle",
    "SdfPartialDiskStyle",
    "SdfPlaneStyle",
    "SdfPointStyle",
    "SdfRegularPolygonStyle",
    "SdfSphereStyle",
    "SdfStyle",
    "Size",
    "SizeSpec",
    "Slider",
    "SliderView",
    "SolidWireframe",
    "SpaceStyle",
    "SpacerView",
    "SphereStyle",
    "SplitView",
    "StackView",
    "Table",
    "TableCellChange",
    "TableColumnAdd",
    "TableRowAdd",
    "TableRowsDelete",
    "TableView",
    "TextArea",
    "TextAreaView",
    "TextField",
    "TextFieldView",
    "TextureLabelStyle",
    "Timeline",
    "gradient_colors",
    "multi_gradient_colors",
    "TitleStyle",
    "TranslatorStyle",
    "ValueEdit",
    "ValueEditView",
    "View",
    "View2DConfig",
    "View3dConfig",
    "Visualizer",
    "VisualizerApp",
    "VizGroup",
    "VizInputType",
    "VizObjectRef",
    "VizOverlayObject",
    "VizSceneHandle",
    "VizSceneObject",
    "VizStyle",
    "VizStyles",
    "WireframeDashPattern",
    "copy_theme",
    "default_theme",
    "external_theme_dirs",
    "list_themes",
    "register_theme",
    "theme_css_files",
    "theme_label",
]
